### PR TITLE
chore(project): configure eslint imports sorter

### PR DESCRIPTION
**Pull request by vanbasten17**
## Description
Added eslint rule to fail if imports are not sorted.
If all of us are agree, when we have pending PRs closed, we can run it with: Run `npx eslint 'path-to-be-sorted' --fix`

Sorted all imports for packages and run prettier for all of them.
from within `packages`:

`npx eslint package --fix; ../node_modules/.bin/prettier --write --config ../.prettierrc package`

### CODE REVIEW

**Comment by dpinol** [comment]
we'll never have 0 open branches.
go ahead and apply the rule to see that it breaks nothing (try botonic serve and deploy).
when closed, warn everybody so that we merge

@marcpdw in a few weeks in no issues arise, I suggest you to apply it to frontend

**Review by dpinol — APPROVED** [review]
:clap:

**Review by ericmarcos — APPROVED** [review]
Agree with @dpinol comments

**Comment by vanbasten17** [comment]
@dpinol , @ericmarcos , i have applied the import sorter and prettier to every package and website. If you want, you can take a quick look to the files changed 👍

**Comment by vanbasten17** [comment]
i will publish a 0.16.0-alpha.0 for every package and test that everything works as expected. If so, i will proceed with the merge.

**Pull request merged**
