### PR TITLE
Feat/enable lint GitHub actions

### PR DESCRIPTION
**Pull request by MarcosCA**
this PR depends on this one :
https://github.com/hubtype/botonic/pull/513

### CODE REVIEW

**Comment by dpinol** [comment]
@MarcosCA please rebase

**Comment by dpinol** [comment]
@MarcosCA when a PR depends on another one, please refer to it on the PR so that the reviewer knows which commits must be reviewed. In this case that there are many commits I suggest changing the base branch to the one from the other PR

**Comment by dpinol** [comment]
@MarcosCA please rebase again: "This branch cannot be rebased due to conflicts"

**Comment by MarcosCA** [comment]
> @MarcosCA please rebase again: "This branch cannot be rebased due to conflicts"

I'm having lots of conflict on rebase because I have been working on same files over an over. I'll do squash and merge.

**Comment by dpinol** [comment]
> > @MarcosCA please rebase again: "This branch cannot be rebased due to conflicts"
> 
> I'm having lots of conflict on rebase because I have been working on same files over an over. I'll do squash and merge.

yes, that's a good practice in this case :+1:

**Pull request merged**
