### PR TITLE
Chore/ci configure nlu tests #208

### PR DESCRIPTION
**Pull request by manuelfidalgo**
## Description
Execute nlu tests in github actions when pushing changes

## Context
NLU had already tests but they were NOT being executing in github actions.
We need to execute them if we want to have a more realistic coverage measure.

## Approach taken / Explain the design
Configure test execution and upload the coverage reports to codecov in the botonic-nlu-tests.yml file.
Also introduce a step for creating a report with test results

## To document / Usage example
Triggered when there is push related to nlu package

## Testing
See this test execution with the changes: https://github.com/hubtype/botonic/runs/1687445867

## Note 
Currently the tests are failing in github actions, a separated task ~~will be created~~ has been created in linear to investigate the issue: https://linear.app/hubtype/issue/BOT-208)

### CODE REVIEW

**Review by dpinol — APPROVED** [review]

**Comment by dpinol** [comment]
@vanbasten17  can you fix the unit tests so that they work on CI?

**Comment by vanbasten17** [comment]
sure @dpinol , we'll take a look on it when possible

**Review by vanbasten17 — APPROVED** [review]
@manuelfidalgo fixed one issue regarding the creation of the folder of word-embeddings, increased timeout and grouped related embeddings tests. Go for it :)

**Comment by manuelfidalgo** [comment]
thanks a lot @marcrabat  :green_heart:

**Pull request merged**
